apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
  labels:
    app: docker
spec:
  replicas: 8
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
        - name: cont1
          image: leelanaveen123/docker
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: mysvc1
spec:
  type: NodePort
  selector:
    app: docker
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31100
